public enum CommandType {
    ACCEPT, REJECT, DISCONNECT, MESSAGE, HELLO_SERVER, HELLO_CLIENT, CALL, LOGIN, SIGNUP, DISCONNECT_FROM_USER,
    CONTACTS, GET_CONTACTS, ONLINE_CONTACTS, LOGOUT, OFFLINE, GET_MY_CONTACTS, EMPTYCONTACTS, EMPTYMYCONTACTS, BUSY, MY_CONTACTS
}
