public enum CommandType {
    ACCEPT, REJECT, DISCONNECT, NICK, MESSAGE, HELLO_SERVER, HELLO_CLIENT, CALL, LOGIN, SIGNUP, DISCONNECT_FROM_USER,
    CONTACTS, GET_CONTACTS, CONTACT, ONLINE_CONTACTS,LOGOUT
}
